/**
 * Operational copy for the Reception workspace — plain language for front-desk staff.
 * Prefer these labels over product or technical terms (Smart Intake, MPI, OCR, etc.).
 */

export const RECEPTION_COPY = Object.freeze({
  workspace: {
    eyebrow: 'Front desk',
    title: 'Reception',
    description: 'Register patients, confirm who they are, and send them to the triage nurse.',
    deskDescription: 'Register patients and send them to the triage nurse.',
    actionsLabel: 'Register a patient',
    registerWalkIn: 'Register walk-in',
    checkIdentity: 'Check ID & documents',
    otherArrivals: 'Other arrivals',
    sentToTriage: 'ready for the triage nurse',
    openPatientCard: 'Open patient card',
    viewWhiteboard: 'View on whiteboard',
    seeInList: 'See in waiting list',
    registerNext: 'Register next patient',
  },
  search: {
    idle: 'Search patient, encounter, referral, EMS, or queue in the bar above — press',
    filtering: 'Showing results for',
    filteringSuffix: '— use the search bar above for patient actions.',
    focus: 'Go to search',
    refine: 'Refine search',
  },
  chooser: {
    eyebrow: 'Other arrival types',
    title: 'How is this patient arriving?',
    description: 'Use these when the main register button is not the right fit.',
    fullIdentity: 'Full identity check',
    fullIdentityHint: 'Match records, review documents, allergies, and medications',
    scanId: 'Scan ID card',
    scanIdHint: 'Take a photo of ID or health card',
    walkIn: 'Register walk-in',
    walkInHint: 'Name, date of birth, and reason for visit — fastest option',
    withSymptoms: 'Register with symptoms',
    withSymptomsHint: 'Add complaint, vitals, and urgency before sending to nurse',
    unknown: 'Patient unknown',
    unknownHint: 'Send to triage nurse while identity is still being sorted out',
  },
  artifactPicker: {
    eyebrow: 'Document capture',
    title: 'What are you capturing?',
    description: 'Choose the document type so CareDroid extracts the right fields for staff review.',
  },
  queues: {
    sectionTitle: 'Arrivals & waiting lists',
    listsTitle: "Today's lists",
    tabs: Object.freeze({
      ems: 'Ambulance arrivals',
      verification: 'Need ID check',
      pretriage: 'Waiting for nurse',
    }),
    empty: Object.freeze({
      ems: 'No ambulance patients waiting to register.',
      verification: 'No patients waiting for an ID check.',
      pretriage: 'No patients waiting for the triage nurse.',
    }),
    rowActionVerify: 'Check ID',
    rowActionEms: 'Ambulance',
  },
  metrics: Object.freeze({
    arrivalsToday: 'Today',
    awaitingVerification: 'ID check',
    awaitingTriage: 'Awaiting nurse',
    rapidReview: 'Rapid review',
    emsInbound: 'EMS inbound',
    queueSize: 'On lists',
    dataQualityRisks: 'Data gaps',
    queueOverdue: 'Overdue',
    longestWait: 'Longest wait',
    triageBreachRisk: 'Triage risk',
    triageBreached: 'Triage late',
    doorToTriage: 'Door→triage',
    offloadDelays: 'Offload',
    crowdLevel: 'Crowd',
  }),
  processEducation: Object.freeze({
    eyebrow: 'Patient education',
    title: 'Emergency visit steps for patients',
    intro: 'Share these simple steps when patients ask what happens next.',
  }),
  patientAnswers: Object.freeze({
    eyebrow: 'Front desk brief',
    title: 'Patient answers',
    intro: 'Shareable answers for common waiting-room questions — matches the public wall display.',
    publicDisplayTitle: 'Waiting room status (public display)',
    crowdLevel: 'Crowd level',
    whyWaitTitle: 'Why is the wait long?',
    processTitle: 'Emergency visit steps',
    whereAmI: 'Where am I in the process?',
    whatNext: 'What happens next?',
    nextCheckpoint: 'Next checkpoint',
    contactOverdue: 'Staff contact is overdue for this patient.',
    selectPatientHint: 'Select a patient from the queue to see personalized answers and highlight their step.',
    openPatient: 'Open patient chart',
  }),
  arrivalControl: Object.freeze({
    stripLabel: 'Arrival control snapshot',
    recentArrivals: 'Recent arrivals',
    awaitingRegistration: 'Awaiting registration',
    triagePending: 'Triage pending',
    rapidReview: 'Rapid review',
    inWaitingRoom: 'In waiting room',
    safetyFlags: 'Quick safety flags',
  }),
  ems: {
    eyebrow: 'Ambulance updates',
    title: 'Incoming ambulances',
    description: 'See who is on the way and start their chart before they arrive.',
    refresh: 'Refresh',
    refreshing: 'Refreshing…',
    loading: 'Loading ambulance list…',
    empty: 'No ambulances on the way right now.',
    prepareChart: 'Start their chart',
    registerNow: 'Ambulance arrived — register now',
  },
  recentArrivals: {
    title: 'Just arrived',
    subtitle: 'Patients registered in the last 30 minutes.',
    empty: 'No one registered in the last 30 minutes.',
  },
  duplicate: {
    bannerTitle: 'This patient may already be here',
    bannerDescription:
      'We found a similar record. Open the existing chart before creating a new one.',
    alertTitle: 'Possible duplicate — check before registering',
    alertDescription: 'Open the existing chart or confirm this is a different person.',
    openChart: 'Open chart',
    openVerification: 'Check identity',
    identityPending: 'Identity unclear — send to nurse anyway',
    notDuplicate: 'Different person — continue',
  },
  express: {
    title: 'Register walk-in',
    subtitle: 'Tab between fields · Enter to finish · patient goes to triage nurse',
    submit: 'Register & send to nurse',
    submitting: 'Registering…',
  },
  quickIntake: {
    title: 'Quick intake',
    subtitle: 'Search or type name · Tab through fields · Enter to register and send to triage',
    searchLabel: 'Search patient',
    searchPlaceholder: 'Name, MRN, DOB, phone, or health card',
    patientNameLabel: 'Patient name',
    patientNamePlaceholder: 'First and last name',
    optionalIdentity: 'Optional — if available',
    quickNotesPlaceholder: 'Interpreter, wheelchair, escort…',
    safetyDetails: 'Safety flags (optional)',
    submit: 'Start encounter & send to queue',
    submitting: 'Sending to queue…',
    closeLabel: 'Close quick intake',
    registerNext: 'Register next patient',
  },
  quickCreate: {
    title: 'Register with symptoms',
    submit: 'Register & send to nurse',
    submitting: 'Registering…',
    closeLabel: 'Close registration form',
  },
  identityCheck: {
    overlayLabel: 'Check patient identity',
    title: 'Check patient identity',
    description:
      'Confirm name, date of birth, and health card. Link to an existing chart or register as new.',
    begin: 'Begin check',
    starting: 'Starting…',
    sessionActive: 'Check in progress',
    close: 'Close',
    backToReception: 'Back to Reception',
    aiHelp: 'Get help',
    aiHelpLoading: 'Getting help…',
    steps: Object.freeze([
      'Document & details',
      'Find match',
      'Confirm fields',
      'Finish',
    ]),
  },
  header: {
    register: 'Register',
    registerTitle: 'Register a walk-in patient',
    searchLabel: 'Patient search',
  },
  commandPalette: {
    newPatientClerk: 'Register walk-in',
    newPatientClerkDescription: 'Fast registration on the reception desk — sent to triage nurse.',
    newPatientOther: 'Check ID & register',
    newPatientOtherDescription: 'Identity check with document scan before registering.',
    patientLookupClerk: 'Search arriving patients',
  },
  searchResults: {
    filterQueues: 'Filter waiting lists',
    newPatient: 'Register new patient',
    noMatch: 'no match for',
  },
  copilot: Object.freeze({
    eyebrow: 'Reception Copilot',
    title: 'Reception Copilot',
    autoUpdated: 'Auto-updated',
    idle: 'Copilot updates as you capture chief complaint and critical fields.',
    outstandingTitle: 'Still needed before routing',
    outstandingNone: 'Nothing outstanding — ready to route.',
    triageSignOffEyebrow: 'Reception Copilot · nurse triage sign-off',
  }),
  escalation: Object.freeze({
    eyebrow: 'Front desk escalation',
    title: 'Flag for triage / charge nurse',
    description:
      'Send an urgent signal to triage or charge nurse without leaving reception. They will see it in their alert center.',
    openAction: 'Escalate to nurse',
    reasonLegend: 'What is happening?',
    patientLabel: 'Patient (optional for collapse / desk events)',
    noPatientLinked: 'No patient linked',
    detailLabel: 'What should the nurse know?',
    detailPlaceholder: 'Location, symptoms, identity concern, or duplicate chart details…',
    submit: 'Notify triage / charge',
    submitting: 'Sending…',
    submitSuccess: 'Escalation sent',
    submitError: 'Could not send escalation — try again.',
    confirmationTitle: 'Nurse team notified',
    confirmationBody: 'You can stay on reception. Triage and charge nurse will respond from their workflow.',
    flagAnother: 'Flag another concern',
  }),
});
