/**
 * CareDroid architecture artifact registry — harmonization audit surface.
 * Classifications drive consolidation work; not a second permission system.
 */
export const EMERGENCY_ARCHITECTURE_CLASSIFICATION = Object.freeze({
  ACTIVE_ROLE_LOGIC: 'ACTIVE_ROLE_LOGIC',
  ACTIVE_SCREEN_LOGIC: 'ACTIVE_SCREEN_LOGIC',
  ACTIVE_DISPLAY_MODE: 'ACTIVE_DISPLAY_MODE',
  DUPLICATE: 'DUPLICATE',
  DISCONNECTED: 'DISCONNECTED',
  LEGACY: 'LEGACY',
  FUTURE_MODULE: 'FUTURE_MODULE',
  DEAD_SAFE_TO_REMOVE: 'DEAD_SAFE_TO_REMOVE',
  NEEDS_MANUAL_REVIEW: 'NEEDS_MANUAL_REVIEW',
});

export type EmergencyArchitectureClassification =
  (typeof EMERGENCY_ARCHITECTURE_CLASSIFICATION)[keyof typeof EMERGENCY_ARCHITECTURE_CLASSIFICATION];

export type EmergencyArchitectureArtifact = {
  id: string;
  path: string;
  classification: EmergencyArchitectureClassification;
  canonical?: string;
  note?: string;
};

/** Curated inventory for role/screen harmonization — extend as artifacts are retired. */
export const EMERGENCY_ARCHITECTURE_REGISTRY: readonly EmergencyArchitectureArtifact[] = Object.freeze([
  {
    id: 'emergency-permission-registry',
    path: 'src/config/emergencyPermissionRegistry.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_ROLE_LOGIC,
    note: 'Canonical permission keys — actions, routes, screens, display modes',
  },
  {
    id: 'emergency-role-permissions',
    path: 'src/config/emergencyRolePermissions.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_ROLE_LOGIC,
    canonical: 'src/config/emergencyPermissionRegistry.ts',
    note: 'Role resolution, routes, and backward-compatible action exports',
  },
  {
    id: 'triage-screen-model',
    path: 'src/config/triageScreenModel.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/config/careDroidScreenModeRegistry.ts',
    note: 'TRIAGE_SCREEN widget/action wiring and pretriage handoff paths',
  },
  {
    id: 'reception-screen-model',
    path: 'src/config/receptionScreenModel.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/config/careDroidScreenModeRegistry.ts',
    note: 'RECEPTION_SCREEN widget/action wiring for front-desk workflows',
  },
  {
    id: 'charge-nurse-screen-model',
    path: 'src/config/chargeNurseScreenModel.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/config/careDroidScreenModeRegistry.ts',
    note: 'CHARGE_NURSE_SCREEN widget/action wiring for flow command surfaces',
  },
  {
    id: 'physician-screen-model',
    path: 'src/config/physicianScreenModel.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/config/careDroidScreenModeRegistry.ts',
    note: 'PHYSICIAN_SCREEN widget/action wiring for clinical review surfaces',
  },
  {
    id: 'ems-screen-model',
    path: 'src/config/emsScreenModel.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/config/careDroidScreenModeRegistry.ts',
    note: 'EMS_SCREEN widget/action wiring for inbound, handoff, and offload surfaces',
  },
  {
    id: 'public-waiting-screen-model',
    path: 'src/config/publicWaitingScreenModel.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_DISPLAY_MODE,
    canonical: 'src/config/careDroidScreenModeRegistry.ts',
    note: 'PUBLIC_WAITING_DISPLAY PHI-safe widget wiring for waiting-room walls',
  },
  {
    id: 'public-waiting-display-model',
    path: 'src/components/whiteboard/publicWaitingDisplayModel.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_DISPLAY_MODE,
    canonical: 'src/config/publicWaitingScreenModel.ts',
    note: 'Aggregate snapshot builder — wait range, crowd level, guidance, status messaging, escalation',
  },
  {
    id: 'waiting-room-status-messaging',
    path: 'src/services/waitingRoomStatusMessaging.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_DISPLAY_MODE,
    canonical: 'src/config/publicWaitingScreenModel.ts',
    note: 'PHI-safe waiting-room status copy for public displays and front-desk visibility',
  },
  {
    id: 'arrival-control-layer',
    path: 'src/services/arrivalControlLayer.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/components/reception/receptionQueueModel.ts',
    note: 'Arrival-to-triage control — timestamps, modes, safety flags, queue routing, operational sync',
  },
  {
    id: 'reception-journey-timeline',
    path: 'src/components/reception/ReceptionJourneyTimeline.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/arrivalControlLayer.ts',
    note: 'Reception front-door journey timeline — arrival, registration, triage-pending, waiting-room stages with live counts and average wait, drill-through to each queue tab',
  },
  {
    id: 'operational-presentation-model',
    path: 'src/config/emergencyOperationalPresentationModel.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/config/careDroidScreenModeRegistry.ts',
    note: 'Unified operational presentation profiles — emphasis, copy, and strip layout per screen mode',
  },
  {
    id: 'operational-strip-component',
    path: 'src/components/emergency/OperationalStrip.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/config/emergencyOperationalPresentationModel.ts',
    note: 'Single metric strip component with role-aware variants for all CareDroid surfaces',
  },
  {
    id: 'multi-role-workflow-validation',
    path: 'src/services/emergencyMultiRoleWorkflowValidation.test.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/config/emergencyRoleScreenMatrix.ts',
    note: 'End-to-end reception → triage → whiteboard → manager → public display workflow validation',
  },
  {
    id: 'multi-screen-convergence',
    path: 'src/config/emergencyMultiScreenConvergence.test.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/config/careDroidScreenModeRegistry.ts',
    note: 'Final multi-screen convergence — one shell, one state, one permission and privacy model',
  },
  {
    id: 'read-only-whiteboard-screen-model',
    path: 'src/config/readOnlyWhiteboardScreenModel.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_DISPLAY_MODE,
    canonical: 'src/config/careDroidScreenModeRegistry.ts',
    note: 'READ_ONLY_WHITEBOARD widget wiring for hallway and nurse-station operations walls',
  },
  {
    id: 'wall-display-monitor-privacy-model',
    path: 'src/config/wallDisplayMonitorPrivacyModel.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_DISPLAY_MODE,
    canonical: 'src/config/emergencyDisplayPrivacyPolicy.ts',
    note: 'Hallway monitor metric redaction — delegates central-node trigger to display privacy policy',
  },
  {
    id: 'emergency-display-privacy-policy',
    path: 'src/config/emergencyDisplayPrivacyPolicy.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_DISPLAY_MODE,
    canonical: 'src/config/careDroidScreenModeRegistry.ts',
    note: 'Unified PHI redaction resolver for public, hallway, clinical, and command center surfaces',
  },
  {
    id: 'emergency-role-action-matrix',
    path: 'src/config/emergencyRoleActionMatrix.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_ROLE_LOGIC,
    canonical: 'src/config/emergencyPermissionRegistry.ts',
    note: 'Role-action matrix with allowed, disabled, hidden, and readonly presentation states',
  },
  {
    id: 'emergency-role-navigation-model',
    path: 'src/config/emergencyRoleNavigationModel.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/config/emergencyRoleScreenMatrix.ts',
    note: 'Role + screen-mode landing routes for post-login, home, and default redirects',
  },
  {
    id: 'emergency-screen-kpi-policy',
    path: 'src/config/emergencyScreenKpiPolicy.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/config/careDroidScreenModeRegistry.ts',
    note: 'Screen-mode KPI policy — reception, triage, charge nurse, public waiting, command center',
  },
  {
    id: 'emergency-device-context-model',
    path: 'src/config/emergencyDeviceContextModel.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/config/emergencyRoleScreenMatrix.ts',
    note: 'Multi-screen device context — workstation binding to screen mode and kiosk surfaces',
  },
  {
    id: 'command-center-screen-model',
    path: 'src/config/commandCenterScreenModel.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/config/careDroidScreenModeRegistry.ts',
    note: 'COMMAND_CENTER_SCREEN widget wiring for director and throughput-lead surfaces',
  },
  {
    id: 'command-center-throughput-model',
    path: 'src/components/whiteboard/commandCenterThroughputModel.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/config/commandCenterScreenModel.ts',
    note: 'Throughput snapshot builder — arrivals, waits, boarding, LWBS, forecast, system health',
  },
  {
    id: 'care-droid-screen-mode-registry',
    path: 'src/config/careDroidScreenModeRegistry.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    note: 'Canonical screen mode registry — widgets, actions, density, PHI, landing',
  },
  {
    id: 'care-droid-screen-modes',
    path: 'src/config/careDroidScreenModes.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/config/careDroidScreenModeRegistry.ts',
    note: 'Re-export surface for central node and hooks',
  },
  {
    id: 'emergency-role-screen-matrix',
    path: 'src/config/emergencyRoleScreenMatrix.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/config/careDroidScreenModeRegistry.ts',
    note: 'Role → screen-mode resolver and display query handling',
  },
  {
    id: 'care-droid-central-node',
    path: 'src/central-node/careDroidCentralNode.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    note: 'Screen mode config + operational snapshot',
  },
  {
    id: 'use-route-screen-mode',
    path: 'src/hooks/useRouteScreenMode.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'emergencyRoleScreenMatrix.resolveEmergencyScreenMode',
  },
  {
    id: 'use-whiteboard-display-mode',
    path: 'src/hooks/useWhiteboardDisplayMode.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_DISPLAY_MODE,
  },
  {
    id: 'use-screen-mode-capabilities',
    path: 'src/hooks/useScreenModeCapabilities.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
  },
  {
    id: 'whiteboard-density-model',
    path: 'src/config/whiteboardDensityModel.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_DISPLAY_MODE,
  },
  {
    id: 'department-status-screen',
    path: 'src/components/whiteboard/DepartmentStatusScreen.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_DISPLAY_MODE,
    note: 'Public / read-only wall display',
  },
  {
    id: 'unified-navigation',
    path: 'src/config/unified-navigation.config.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_ROLE_LOGIC,
  },
  {
    id: 'utils-emergency-role-permissions',
    path: 'src/utils/emergencyRolePermissions.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.DUPLICATE,
    canonical: 'src/config/emergencyPermissionRegistry.ts',
    note: 'Legacy MD/RN boolean flags',
  },
  {
    id: 'layout-app-shell',
    path: 'src/layouts/AppShell.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.LEGACY,
    canonical: 'src/components/AppShell.tsx',
  },
  {
    id: 'reassessment-timer-engine',
    path: 'src/engine/reassessmentTimerEngine.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    note: 'Unified reassessment timer engine — arrival, triage, nurse contact, vitals, due/overdue',
  },
  {
    id: 'reassessment-timer-strip',
    path: 'src/components/reassessment/ReassessmentTimerStrip.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/engine/reassessmentTimerEngine.ts',
    note: 'Compact timer strip for whiteboard cards and waiting room safety board rows',
  },
  {
    id: 'reassessment-automation-service',
    path: 'src/services/reassessmentAutomationService.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.DISCONNECTED,
    canonical: 'src/engine/reassessmentTimerEngine.ts',
  },
  {
    id: 'ems-offload-tracker',
    path: 'src/services/emsOffloadTracker.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/components/EMSPipeline.tsx',
    note: 'EMS offload tracker — ETA, arrival, handoff timing, delay, bay, owner',
  },
  {
    id: 'ems-offload-tracker-panel',
    path: 'src/components/ems/EmsOffloadTrackerPanel.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/emsOffloadTracker.ts',
    note: 'EMS offload table for EMS screen and whiteboard',
  },
  {
    id: 'ems-offload-attention-strip',
    path: 'src/components/ems/EmsOffloadAttentionStrip.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/emsOffloadTracker.ts',
    note: 'Compact EMS offload status strip for whiteboard and EMS pipeline',
  },
  {
    id: 'ambulance-handoff-checklist',
    path: 'src/services/ambulanceHandoffChecklist.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/components/EMSPipeline.tsx',
    note: 'Structured ambulance handoff checklist — identity, complaint, vitals, meds, flags, acceptance, destination',
  },
  {
    id: 'ambulance-handoff-checklist-panel',
    path: 'src/components/ems/AmbulanceHandoffChecklistPanel.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/ambulanceHandoffChecklist.ts',
    note: 'Interactive EMS handoff checklist panel on EMS pipeline rows',
  },
  {
    id: 'ambulance-handoff-checklist-badge',
    path: 'src/components/ems/AmbulanceHandoffChecklistBadge.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/ambulanceHandoffChecklist.ts',
    note: 'Compact handoff completion badge for EMS rows and operational surfaces',
  },
  {
    id: 'ems-offload-command-center',
    path: 'src/services/emsOffloadCommandCenterService.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.DISCONNECTED,
    canonical: 'src/services/emsOffloadTracker.ts',
  },
  {
    id: 'federated-learning-route',
    path: 'src/config/routes.config.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.FUTURE_MODULE,
  },
  {
    id: 'waiting-room-safety-board-model',
    path: 'src/components/whiteboard/waitingRoomSafetyBoardModel.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/config/chargeNurseScreenModel.ts',
    note: 'Waiting room safety board — vitals, reassessment, provider/test status, high-risk flags',
  },
  {
    id: 'waiting-room-safety-board',
    path: 'src/components/whiteboard/WaitingRoomSafetyBoard.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/components/whiteboard/waitingRoomSafetyBoardModel.ts',
    note: 'Operational waiting room safety table within CareDroid whiteboard and queues surfaces',
  },
  {
    id: 'high-risk-complaint-flags',
    path: 'src/services/highRiskComplaintFlags.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/arrivalControlLayer.ts',
    note: 'High-risk complaint fast flags — staff alert, rapid review routing, no auto-triage',
  },
  {
    id: 'high-risk-complaint-flag-selector',
    path: 'src/components/reception/HighRiskComplaintFlagSelector.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/highRiskComplaintFlags.ts',
    note: 'Reception intake staff toggle for ten high-risk complaint fast flags',
  },
  {
    id: 'high-risk-complaint-attention-strip',
    path: 'src/components/waiting-room/HighRiskComplaintAttentionStrip.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/highRiskComplaintFlags.ts',
    note: 'Reception and whiteboard attention strip for flagged patients needing rapid review',
  },
  {
    id: 'fit-to-wait-pathway',
    path: 'src/services/fitToWaitPathway.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    note: 'Fit-to-sit / fit-to-wait seating pathway — staff classification only, no auto-triage',
  },
  {
    id: 'fit-to-wait-classification-select',
    path: 'src/components/waiting-room/FitToWaitClassificationSelect.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/fitToWaitPathway.ts',
    note: 'Staff selector for five waiting-room seating / disposition classifications',
  },
  {
    id: 'fit-to-wait-attention-strip',
    path: 'src/components/waiting-room/FitToWaitAttentionStrip.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/fitToWaitPathway.ts',
    note: 'Whiteboard attention strip for unclassified and escalated fit-to-wait patients',
  },
  {
    id: 'patient-experience-status',
    path: 'src/services/patientExperienceStatus.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    note: 'Patient experience status layer — maps journey/queue states to understandable labels for staff',
  },
  {
    id: 'patient-experience-status-badge',
    path: 'src/components/patient-experience/PatientExperienceStatusBadge.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/patientExperienceStatus.ts',
    note: 'Staff and PHI-safe patient experience status badge',
  },
  {
    id: 'patient-experience-status-strip',
    path: 'src/components/patient-experience/PatientExperienceStatusStrip.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/patientExperienceStatus.ts',
    note: 'Whiteboard staff summary of experience status counts across active patients',
  },
  {
    id: 'waiting-room-status-messaging',
    path: 'src/services/waitingRoomStatusMessaging.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/patientExperienceStatus.ts',
    note: 'PHI-safe waiting room messaging derived from experience status layer',
  },
  {
    id: 'public-waiting-display-model',
    path: 'src/components/whiteboard/publicWaitingDisplayModel.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/waitingRoomStatusMessaging.ts',
    note: 'Public wall display — aggregate counts and generic messages only, no PHI',
  },
  {
    id: 'queue-reason-visibility',
    path: 'src/services/queueReasonVisibility.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    note: 'Queue reason layer — why each patient remains in queue from existing journey data',
  },
  {
    id: 'queue-reason-badge',
    path: 'src/components/queues/QueueReasonBadge.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/queueReasonVisibility.ts',
    note: 'Per-patient queue reason badges for queue rows and patient cards',
  },
  {
    id: 'queue-reason-attention-strip',
    path: 'src/components/queues/QueueReasonAttentionStrip.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/queueReasonVisibility.ts',
    note: 'Whiteboard strip summarizing dominant queue reasons across active patients',
  },
  {
    id: 'lwbs-risk-layer',
    path: 'src/services/lwbsRiskLayer.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    note: 'Operational LWBS advisory risk — wait, reassessment, contact, congestion, time, complaint',
  },
  {
    id: 'lwbs-risk-badge',
    path: 'src/components/waiting-room/LwbsRiskBadge.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/lwbsRiskLayer.ts',
    note: 'Per-patient LWBS advisory badge for cards and waiting-room board',
  },
  {
    id: 'lwbs-risk-strip',
    path: 'src/components/waiting-room/LwbsRiskStrip.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/lwbsRiskLayer.ts',
    note: 'Whiteboard LWBS advisory summary with elevated/high/medium counts',
  },
  {
    id: 'waiting-room-deterioration-watch',
    path: 'src/services/waitingRoomDeteriorationWatch.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    note: 'Operational deterioration watch — vitals, reassessment, complaint, EMS/intake — advisory only',
  },
  {
    id: 'deterioration-watch-badge',
    path: 'src/components/waiting-room/DeteriorationWatchBadge.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/waitingRoomDeteriorationWatch.ts',
    note: 'Per-patient deterioration watch badge for cards and waiting-room board',
  },
  {
    id: 'deterioration-watch-strip',
    path: 'src/components/waiting-room/DeteriorationWatchStrip.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/waitingRoomDeteriorationWatch.ts',
    note: 'Whiteboard deterioration watch summary with urgent/re-review/watch counts',
  },
  {
    id: 'triage-breach-timer',
    path: 'src/services/triageBreachTimer.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    note: 'Arrival-to-triage breach timer with site thresholds, breach risk, and breached counts',
  },
  {
    id: 'triage-breach-badge',
    path: 'src/components/triage/TriageBreachBadge.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/triageBreachTimer.ts',
    note: 'Per-patient triage breach badge for reception queues and patient cards',
  },
  {
    id: 'triage-breach-panel',
    path: 'src/components/triage/TriageBreachPanel.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/triageBreachTimer.ts',
    note: 'Reception dashboard triage breach summary panel',
  },
  {
    id: 'triage-breach-strip',
    path: 'src/components/triage/TriageBreachStrip.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/triageBreachTimer.ts',
    note: 'Whiteboard triage breach summary with breached and at-risk patient preview',
  },
  {
    id: 'provider-wait-breach-timer',
    path: 'src/services/providerWaitBreachTimer.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    note: 'Triage-to-provider breach timer with CTAS thresholds, high-risk exceptions, and approaching/breached counts',
  },
  {
    id: 'provider-wait-breach-badge',
    path: 'src/components/provider-wait/ProviderWaitBreachBadge.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/providerWaitBreachTimer.ts',
    note: 'Per-patient provider wait breach badge for waiting-room board rows',
  },
  {
    id: 'provider-wait-breach-panel',
    path: 'src/components/provider-wait/ProviderWaitBreachPanel.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/providerWaitBreachTimer.ts',
    note: 'Charge nurse provider wait breach summary panel',
  },
  {
    id: 'provider-wait-breach-strip',
    path: 'src/components/provider-wait/ProviderWaitBreachStrip.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/providerWaitBreachTimer.ts',
    note: 'Whiteboard provider wait breach summary with approaching, breached, and high-risk exception preview',
  },
  {
    id: 'waiting-room-communication-log',
    path: 'src/services/waitingRoomCommunicationLog.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    note: 'Waiting-room staff communication event log from workflow audit, notes, and timeline',
  },
  {
    id: 'waiting-room-communication-badge',
    path: 'src/components/waiting-room/WaitingRoomCommunicationBadge.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/waitingRoomCommunicationLog.ts',
    note: 'Communication recency badge for patient detail and board rows',
  },
  {
    id: 'waiting-room-communication-panel',
    path: 'src/components/waiting-room/WaitingRoomCommunicationPanel.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/waitingRoomCommunicationLog.ts',
    note: 'Patient detail communication event log with recency summary and quick-log actions',
  },
  {
    id: 'waiting-room-communication-quick-log',
    path: 'src/components/waiting-room/WaitingRoomCommunicationQuickLog.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/waitingRoomCommunicationLog.ts',
    note: 'Staff quick-log buttons for waiting-room communication events',
  },
  {
    id: 'reception-escalation-workflow',
    path: 'src/services/receptionEscalationWorkflow.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    note: 'Reception desk escalation flags with triage/charge nurse notification',
  },
  {
    id: 'reception-escalation-panel',
    path: 'src/components/reception/ReceptionEscalationPanel.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/receptionEscalationWorkflow.ts',
    note: 'Reception escalation form — five flag reasons without leaving desk workflow',
  },
  {
    id: 'reception-escalation-quick-actions',
    path: 'src/components/reception/ReceptionEscalationQuickActions.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/receptionEscalationWorkflow.ts',
    note: 'One-tap reception escalation flags for desk staff',
  },
  {
    id: 'reception-escalation-attention-strip',
    path: 'src/components/reception/ReceptionEscalationAttentionStrip.tsx',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.ACTIVE_SCREEN_LOGIC,
    canonical: 'src/services/receptionEscalationWorkflow.ts',
    note: 'Triage/charge nurse incoming reception escalation attention strip',
  },
  {
    id: 'waiting-room-intelligence-service',
    path: 'src/services/waitingRoomIntelligenceService.ts',
    classification: EMERGENCY_ARCHITECTURE_CLASSIFICATION.LEGACY,
    canonical: 'src/components/whiteboard/waitingRoomSafetyBoardModel.ts',
    note: 'Superseded by waitingRoomSafetyBoardModel — manual review before removal',
  },
]);

export function listArchitectureArtifacts(
  classification?: EmergencyArchitectureClassification,
): EmergencyArchitectureArtifact[] {
  if (!classification) return [...EMERGENCY_ARCHITECTURE_REGISTRY];
  return EMERGENCY_ARCHITECTURE_REGISTRY.filter((entry) => entry.classification === classification);
}
